name: Python Test

on:
  push:
    branches: ["main"]
    paths-ignore: ["README.md", "docs", ".github"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["README.md", "docs", ".github"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        test_config: ["local", "spark", "azure"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: Yarden-zamir/install-mssql-odbc@main
        with:
          ODBC_VERSION: 18
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install project dependencies incl Spark
        if: matrix.test_config == 'spark'
        run: uv sync --all-extras --group test --group dev --group spark
      - name: Install project dependencies
        if: matrix.test_config != 'spark'
        run: uv sync --all-extras --group test --group dev
      - name: Pyright
        run: |
          uv run pyright odbc2deltalake
      - name: Test with pytest
        run: uv run -m pytest -x --cov=odbc2deltalake tests
        env:
          ODBCLAKE_TEST_CONFIGURATION: ${{ matrix.test_config }}
